version: '3.8'
services:
  app:
    image: fibonacci-application:latest
    build: .
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.0.39
    environment:
      MYSQL_DATABASE: fibonacci_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    links:
      - node-exporter
      - cadvisor

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"

volumes:
  db_data:
  grafana_data:













































#version: '3.8'
#services:
#  app:
#    image: fibonacci-application:latest
#    build: .
#    ports:
#      - "8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fibonacci_db
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: Password1776+
#    depends_on:
#      - db
#    deploy:
#      replicas: 3
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: 256M
#      restart_policy:
#        condition: on-failure
#
#  db:
#    image: mysql:8.0.39
#    environment:
#      MYSQL_DATABASE: fibonacci_db
#      MYSQL_ROOT_PASSWORD: Password1776+
#    ports:
#      - "3307:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    restart: always
#
#  prometheus:
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#
#  grafana:
#    image: grafana/grafana:latest
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana_data:/var/lib/grafana
#
#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:latest
#    ports:
#      - "8080:8080"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /sys:/sys
#      - /var/lib/docker/:/var/lib/docker
#
#  node-exporter:
#    image: prom/node-exporter:latest
#    ports:
#      - "9100:9100"
#
#volumes:
#  db_data:
#  grafana_data:
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
