name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: |
          docker build -t jesemeil/fibonacci-application:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push jesemeil/fibonacci-application:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to EC2 instance and deploy application and database
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull jesemeil/fibonacci-application:latest
            
            # Stop and remove existing application container
            docker stop fibonacci-application || true
            docker rm fibonacci-application || true
            
            # Run application container
            docker run -d --name fibonacci-application -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/fibonacci_db \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              jesemeil/fibonacci-application:latest
            
            # Pull the latest MySQL image
            docker pull mysql:8.0.39
            
            # Stop and remove existing database container
            docker stop fibonacci-db || true
            docker rm fibonacci-db || true
            
            # Run database container
            docker run -d --name fibonacci-db -p 3307:3306 \
              -e MYSQL_DATABASE=fibonacci_db \
              -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
              mysql:8.0.39


































#name: CI/CD Pipeline

#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#
#      - name: Build with Maven
#        run: mvn clean package -DskipTests
#
#      - name: Build Docker Image
#        run: |
#          docker build -t jesemeil/fibonacci-application:latest .
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Push Docker Image
#        run: |
#          docker push jesemeil/fibonacci-application:latest
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: SSH to EC2 instance and pull the latest Docker image
#        uses: appleboy/ssh-action@v0.1.7
#        with:
#          host: ${{ secrets.AWS_EC2_HOST }}
#          username: ${{ secrets.AWS_EC2_USERNAME }}
#          key: ${{ secrets.AWS_EC2_SSH_KEY }}
#          script: |
#            docker pull jesemeil/fibonacci-application:latest
#            docker stop fibonacci-application || true
#            docker rm fibonacci-application || true
#            docker run -d --name fibonacci-application -p 8080:8080 jesemeil/fibonacci-application:latest
